<a href="https://colab.research.google.com/github/FranciscoBenvindo/alura-git/blob/main/Numpy_an%C3%A1lise_num%C3%A9rica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np


In [49]:
import pandas as pd
apples = pd.read_csv ('apples_ts.csv')
apples

Unnamed: 0  1.2013  2.2013  3.2013  4.2013  5.2013  6.2013  7.2013  \
0        Moscow   79.72   81.08   79.68   79.80   80.63   80.80   80.28   
1   Kaliningrad   42.67   44.37   44.73   46.75     NaN   51.59   57.80   
2    Petersburg   62.55   62.73   63.43   63.83   66.06   69.22   72.07   
3     Krasnodar   48.26   51.01   50.91   53.94   61.27   65.44   56.51   
4  Ekaterinburg   71.25   71.35   70.90   71.92   72.91   74.39   73.10   

   8.2013  9.2013  ...  6.2019  7.2019  8.2019  9.2019  10.2019  11.2019  \
0   78.99   76.77  ...  116.91  125.29  123.94  113.03   102.19    97.83   
1   62.14   56.76  ...   79.20   80.85   85.33   75.02    77.95    78.98   
2   69.31   65.18  ...  115.35  123.03  123.08  109.71    97.22    95.75   
3   53.00   43.87  ...  102.01  116.12   92.06   82.70    66.62    68.11   
4   70.24   69.12  ...  121.68  125.32  123.41  108.48    98.73    96.25   

   12.2019  1.2020  2.2020  3.2020  
0   101.07  103.44  108.23  110.28  
1    76.55   74.89   70.00   81.53  
2    97.09   98.18  103.10  110.60  
3    73.48   82.04   81.19   95.05  
4   100.12  101.29  102.81  108.53  

[5 rows x 88 columns]

In [50]:
bytebank = pd.read_csv('bytebank.csv')
bytebank

Meses    Valor
0     3.0  5182.17
1     NaN      NaN
2     1.0  5060.00
3     2.0  5120.72
4     5.0  5307.29
5     6.0  5370.97
6     7.0  5435.43
7     8.0  5500.65
8     9.0  5566.66
9    10.0  5633.46
10   11.0  5701.06
11   12.0  5769.47

In [51]:
citrus = pd.read_csv('citrus.csv')
citrus

nome  diametro    peso  vermelho  verde  azul
0         orange      2.96   86.76       172     85     2
1         orange      3.91   88.05       166     78     3
2         orange      4.42   95.17       156     81     2
3         orange      4.47   95.60       163     81     4
4         orange      4.48   95.76       161     72     9
...          ...       ...     ...       ...    ...   ...
9995  grapefruit     15.35  253.89       149     77    20
9996  grapefruit     15.41  254.67       148     68     7
9997  grapefruit     15.59  256.50       168     82    20
9998  grapefruit     15.92  260.14       142     72    11
9999  grapefruit     16.45  261.51       152     74     2

[10000 rows x 6 columns]

In [52]:
np.loadtxt('apples_ts.csv', delimiter =',', usecols = np.arange(1,88,1))

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

In [53]:
url ='https://raw.githubusercontent.com/alura-cursos/numpy/dados/apples_ts.csv'

In [54]:
dado = np.loadtxt(url, delimiter =',', usecols = np.arange(1,88,1))

In [55]:
dado


array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

In [56]:
import numpy as np

# cria uma lista
lista = [1, 2, 3, 4, 5]

# transforma a lista em um array Numpy
array = np.array(lista)

print("Lista: ", lista)
print("Array: ", array)


Lista:  [1, 2, 3, 4, 5]
Array:  [1 2 3 4 5]


In [57]:
import numpy as np
import time

# cria uma lista com 1000000 elementos
lista = list(range(1000000))

# transforma a lista em um array Numpy
array = np.array(lista)

# começa a cronometrar o tempo para a operação com a lista
start_time = time.time()

# realiza a operação de elevar ao quadrado cada elemento da lista
lista_quadrado = [i**2 for i in lista]

# para o cronômetro
list_time = time.time() - start_time

# começa a cronometrar o tempo para a operação com o array
start_time = time.time()

# realiza a operação de elevar ao quadrado cada elemento do array
array_quadrado = array**2

# para o cronômetro
array_time = time.time() - start_time

print("Tempo da operação com a lista: ", list_time)
print("Tempo da operação com o array: ", array_time)


Tempo da operação com a lista:  0.3448646068572998
Tempo da operação com o array:  0.004132509231567383


In [58]:
lista

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [59]:
array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [60]:
dado.ndim

2

In [61]:
dado.size

522

In [62]:
dado.shape

(6, 87)

In [63]:
dado.T

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14

In [64]:
dado

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

In [65]:
dado.T

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14

In [66]:
dado_transposto = dado.T

In [67]:
dado_transposto.shape

(87, 6)

In [68]:
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/bytebank.csv'
import numpy as np
dado1= np.loadtxt(url, delimiter=',',skiprows=1,dtype=float)
dado1.shape

(12, 2)

In [69]:
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/bytebank.csv'
import numpy as np
dado2= np.loadtxt(url, delimiter=',',skiprows=1,dtype=float)
np.shape(dado2)

(12, 2)

In [70]:
import numpy as np
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/citrus.csv'
dado3 = np.loadtxt(url, delimiter=',',usecols=np.arange(1,6,1),skiprows=1)


In [72]:
dado3

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]])

In [74]:
dado_transposto3 = dados.T
dado_transposto3

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14